### PR TITLE
mongoid5 compatability fix. 

### PR DESCRIPTION
**Pull request by burgalon**
Fix check for mongoid_4? to return true for mongoid5 and above

### CODE REVIEW

**Comment by dzello** [comment]
Thanks!

**Comment by dzello** [comment]
Looks like the build failed but probably something simple? Mind taking a look @burgalon?

**Comment by burgalon** [comment]
Bleh... `uninitialized constant Mongo::Connection`

**Comment by burgalon** [comment]
More specifically 
`/home/travis/build/dzello/mongoid_alize/spec/spec_helper.rb:27:in `block in <top (required)>': uninitialized constant Mongo::Connection (NameError)`

**Pull request merged**
